name: bullseye_lang
version: 0.0.1
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  args: ^1.0.0
  kernel: 0.3.29
  source_span: ^1.0.0
  string_scanner: ^1.0.0
dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0